version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql-script.sql:/docker-entrypoint-initdb.d/mysql-script.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
